### ISSUE TITLE
Two Audit failures. High Severity.

### ISSUE THREAD

**Issue by zubietaroberto** [decent-bet/solido#20]
I already fixed the JS-YAML audit failure. But the web3 failure will be trickier: Thorify requires that Web3 Version in particular, and it does not seem that they are willing to update to a newer Web3 version.

**Comment by molekilla** [comment]
We're going to split the providers into modules for the next release 2.0Sent from HUAWEI Mate 10 Pro-------- Original Message --------Subject: [decent-bet/solido] Two Audit failures. High Severity. (#20)From: Roberto Eduardo Zubieta To: decent-bet/solido CC: Subscribed I already fixed the JS-YAML audit failure. But the web3 failure will be trickier: Thorify requires that Web3 Version in particular, and it does not seem that they are willing to update to a newer Web3 version.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/decent-bet/solido","title":"decent-bet/solido","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/decent-bet/solido"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Two Audit failures. High Severity. (#20)"}],"action":{"name":"View Issue","url":"https://github.com/decent-bet/solido/issues/20"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/decent-bet/solido/issues/20",
"url": "https://github.com/decent-bet/solido/issues/20",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
